//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneratorTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Questions
    {
        public int Question { get; set; }
        public string Phrase { get; set; }
        public int Answer1 { get; set; }
        public int Answer2 { get; set; }
        public int Answer3 { get; set; }
        public int Answer4 { get; set; }
        public int Points { get; set; }
        public int DifficultyLvl { get; set; }
    
        public virtual t_Answers t_Answers { get; set; }
        public virtual t_Answers t_Answers1 { get; set; }
        public virtual t_Answers t_Answers2 { get; set; }
        public virtual t_Answers t_Answers3 { get; set; }
    }
}
