//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneratorTeste
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class testeEntities : DbContext
    {
        public testeEntities()
            : base("name=testeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_Answers> t_Answers { get; set; }
        public virtual DbSet<t_Chapters> t_Chapters { get; set; }
        public virtual DbSet<t_Disciplines> t_Disciplines { get; set; }
        public virtual DbSet<t_Passwords> t_Passwords { get; set; }
        public virtual DbSet<t_Questions> t_Questions { get; set; }
        public virtual DbSet<t_textAnswers> t_textAnswers { get; set; }
        public virtual DbSet<t_Users> t_Users { get; set; }
        public virtual DbSet<PersonalFile> PersonalFile { get; set; }
    }
}
